# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, post-commit, commit-msg]
fail_fast: true
repos:
  # - repo: local
  #   hooks:
  #     - id: stage-commit
  #       name: ---------------- Execution stage commit ----------------------
  #       entry: echo
  #       language: system
  #       stages: [commit]
  #       always_run: true
  # - repo: local
  #   hooks:
  #     - id: stage-commit
  #       name: ---------------- Execution stage commit-msg ------------------
  #       entry: echo
  #       language: system
  #       stages: [commit-msg]
  #       always_run: true
  # - repo: local
  #   hooks:
  #     - id: stage-commit
  #       name: ---------------- Execution stage post-commit ------------------
  #       entry: echo
  #       language: system
  #       stages: [post-commit]
  #       always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-symlinks
        stages: [commit]
      - id: check-yaml
        stages: [commit]
        exclude: (template|ci).*\.(json|yml|yaml)$
      - id: check-added-large-files
        stages: [commit]
        args: [--maxkb=10000]
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [commit]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.0.0' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        exclude: .*\.(postcssrc|eslintrc).(js)
        args: ['--fix']
        stages: [commit]
        verbose: true

  # - repo: https://github.com/eliecer2000/commitlint-pre-commit-hook
  #   rev: 'v9.4.0'
  #   hooks:
  #     - id: commitlint
  #       stages: [commit-msg]
  #       always_run: true

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8' # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        stages: [commit]
        always_run: true
        exclude: >
          (?x)^(
              (.*)/static/vendors|
              (.*)/static/ico|
              ^.+\.html$|
              ^.+\.d.ts$|
              cdk.out\**$|
              package-lock.json|
              yarn.lock|
              CHANGELOG.md|
              (.*)\.vtl$|
              ^\*\\__test__\\\*\*\.test\.\*$|
              ^.+\.min\.(js|css)$
          )$
        additional_dependencies:
          - prettier@2.2.1

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: [--exclude=templates/]
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1 # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        files: ^source/
        types: [file, python]
        stages: [commit]

  - repo: https://github.com/1davidmichael/pre-commit-cdk-synth
    rev: v0.0.2
    hooks:
      - id: cdk-synth
        stages: [commit]
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.86.2 # The version of cfn-lint to use
    hooks:
      - id: cfn-lint-rc
        stages: [commit]
  # - repo: https://github.com/fabasoad/pre-commit-snyk
  #   rev: v0.5.0
  #   hooks:
  #     - id: snyk-iac
  #       args: ['cdk.out', '--severity-threshold=critical']
  #       stages: [commit]
